MAX_DOWNLOADS_PER_REQUEST = 3

TASK_STATE_PENDING = "PENDING"
TASK_STATE_PROGRESS = "PROGRESS"
TASK_STATE_SUCCESS = "SUCCESS"
TASK_STATE_FAILURE = "FAILURE"

API_STATUS_PENDING = "pending"
API_STATUS_PROGRESS = "progress"
API_STATUS_COMPLETED = "completed"
API_STATUS_FAILED = "failed"

POST = "POST"
GET = "GET"

LIMIT = 10
OFFSET = 1
